CREATE TABLE users (
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    first VARCHAR(256) NOT NULL,
    last VARCHAR(256) NOT NULL,
    username VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL
);